### PR TITLE
[WIP][Experimental] Automated way of generating cwl Files.

### PR DESCRIPTION
**Pull request by vishnu667**
Issue : #6 

Trying to generate cwl files automatically using `inspect.signature`. 

TODO: 

- [ ] Decide how to handle data_types.
- [ ] Confirmation on how to store files.
- [ ] Write Test Cases.
- [x] Automatically Fetch all Operators and Sensors defined.
- [x] Ability to separate operators from sensors.
- [x] Get the parameter list automatically for each operator.

### CODE REVIEW

**Comment by vishnu667** [comment]
@trejas would like your thoughts on this. And Can you attach a license to the project?

I just put the py file in the bin directory.
And the cwl file input data-type is wrong. Will work on it based on your comments.

Generated Files.
```
├── operator
│   ├── BashOperator.txt
│   ├── BranchPythonOperator.cwl
│   ├── DummyOperator.cwl
│   ├── DummySkipOperator.cwl
│   ├── ExternalTaskMarker.cwl
│   ├── LatestOnlyOperator.cwl
│   ├── PigOperator.cwl
│   ├── PythonOperator.cwl
│   ├── PythonVirtualenvOperator.cwl
│   ├── ShortCircuitOperator.cwl
│   ├── SimpleHttpOperator.cwl
│   ├── SubDagOperator.cwl
│   ├── TriggerDagRunOperator.cwl
└── sensor
    ├── ExternalTaskSensor.cwl
    └── HttpSensor.txt

```

Example of the cwl files generated by the code. 
[BashOperator.cwl](https://github.com/trejas/chartis/files/4928958/BashOperator.txt)
[HttpSensor.cwl](https://github.com/trejas/chartis/files/4928960/HttpSensor.txt)

**Comment by trejas** [comment]
License added. 

https://github.com/trejas/chartis/pull/9

**Comment by trejas** [comment]
This looks like an awesome start. This does generate all of the basic operators. 

@vishnu667 How are you thinking that we would add contributed and custom operators.

Also, it would be good to be able to specify the root path for where the operators are generated, instead of being forced into: `<working directory>/composer?*` 

For the data typing, I have considered something similar to this:
https://github.com/trejas/chartis/pull/4#pullrequestreview-446922750

Unfortunately, this is not a clean solution. I'm open to suggestions as to how to provide data types to the functions.

**Comment by trejas** [comment]
Also, I generally use black formatter for code. Keeps the style consistent.

https://black.readthedocs.io/en/stable/

**Comment by vishnu667** [comment]
Custom operators should not be a problem. As the code looks for all implementation of the base operator. But the data type is going to be problematic. Since we won't know what type the data is being expected. We can get the data type from ones which have default values that are not none. But will have to figure out a better way. If not it will be difficult to maintain.

**Comment by trejas** [comment]
@vishnu667 

Have been searching for a way to handle this appropriately. 

What do you think about the following?

```
import typing
from airflow.operators.python import PythonOperator

print(typing.get_type_hints(PythonOperator.__init__))
```

Types could be coerced during parsing. This would not require any knowledge of type conversion in the interface. It would only require the user to enter the param value with a specific string format.

**Comment by trejas** [comment]
Thinking about this some more. This will only work where type hints have been provided for the __init__ functions of the airflow operators, which looks like they are going to be added in the 2.0 release.

**Comment by trejas** [comment]
Going to handle this 2 ways:

Pre-Airflow 2.0:
```  
 - 'sbg:toolDefaultValue': Datetime
    id: start_date
    type: string
```

Post-Airflow 2.0:
Using type hints from the operator class __init__ function, see [comment](https://github.com/trejas/chartis/pull/8#issuecomment-683315469)

**Comment by trejas** [comment]
Closing, moved to PR #10

**Pull request closed without merging**
